import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import e_Agriculture.e_agriculture;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PRATAP KUMAR
 */
public class newregister extends javax.swing.JFrame {
    Connection conn=null;
    

    /**
     * Creates new form newregister
     */
    public newregister() {
        initComponents();
        conn=e_agriculture.ConnecrDb(); 
   /* String a=jTextField1.getText();
       String b=jPasswordField1.getText();
       String c=jTextField3.getText();
       String d=jTextField4.getText();
       String k=jTextField5.getText();
       String f=jTextField6.getText();
       String g=jTextField7.getText();*/}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1850, 1080));
        setPreferredSize(new java.awt.Dimension(1720, 995));
        getContentPane().setLayout(null);

        jLabel25.setFont(new java.awt.Font("Algerian", 2, 36)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 255));
        jLabel25.setText("Aadhar No");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(690, 190, 420, 22);

        jLabel26.setFont(new java.awt.Font("Algerian", 2, 36)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 255));
        jLabel26.setText("Area of Land(in arcs)");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(680, 540, 480, 22);

        jLabel27.setFont(new java.awt.Font("Algerian", 2, 36)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 255));
        jLabel27.setText("Full Name");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(690, 260, 390, 22);

        jLabel28.setFont(new java.awt.Font("Algerian", 2, 36)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 255));
        jLabel28.setText("Password");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(690, 340, 390, 22);

        jLabel29.setFont(new java.awt.Font("Algerian", 2, 36)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 255));
        jLabel29.setText("Phone No");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(690, 400, 390, 22);

        jLabel30.setFont(new java.awt.Font("Algerian", 2, 36)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 255));
        jLabel30.setText("Address");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(690, 480, 370, 22);

        jLabel31.setFont(new java.awt.Font("Algerian", 2, 36)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 255));
        jLabel31.setText("Type of Land");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(680, 600, 420, 22);

        jLabel32.setFont(new java.awt.Font("Algerian", 2, 36)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 255));
        jLabel32.setText("Survey No");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(690, 670, 390, 22);

        jTextField21.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(jTextField21);
        jTextField21.setBounds(1160, 190, 220, 40);

        jTextField17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField17);
        jTextField17.setBounds(1160, 260, 220, 40);

        jPasswordField3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jPasswordField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField3);
        jPasswordField3.setBounds(1160, 330, 220, 40);

        jTextField18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(jTextField18);
        jTextField18.setBounds(1160, 390, 220, 40);

        jTextField19.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(jTextField19);
        jTextField19.setBounds(1160, 460, 220, 40);

        jTextField20.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(jTextField20);
        jTextField20.setBounds(1160, 530, 220, 40);

        jTextField15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(jTextField15);
        jTextField15.setBounds(1160, 590, 220, 40);

        jTextField16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(jTextField16);
        jTextField16.setBounds(1160, 660, 220, 40);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(950, 730, 150, 31);

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("New Register");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(890, 100, 450, 50);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/38974425-farming-wallpapers.jpg"))); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(10, -30, 1860, 920);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String a=jTextField17.getText();
       String b=jPasswordField3.getText();
       String c=jTextField18.getText();
       String d=jTextField19.getText();
       String k=jTextField20.getText();
       String f=jTextField15.getText();
       String g=jTextField16.getText();
       String h=jTextField21.getText();
       
    
      
       if("".equals(a) && "".equals(b) && "".equals(c) &&  "".equals(d) && "".equals(k) && "".equals(f) && "".equals(g) && "".equals(h))
       {
           JOptionPane.showMessageDialog(this,"please enter valid details");
       }
        else if(  c.length()>10 ||   c.length()<10&& h.length()>12 || h.length()<12 )
      {
          
      JOptionPane.showMessageDialog(null,"plese enter valid number");
      }
      else{

       
       try{
          Statement s =conn.createStatement();
          String s1=("insert into register values('"+h+"','"+a+"','"+b+"','"+c+"','"+d+"','"+k+"','"+f+"','"+g+"');");
          System.out.println("success");
          JOptionPane.showMessageDialog(this," sucessfully registered");
          s.executeUpdate(s1);
          
       }
       catch(SQLException e)
       {
           Logger.getLogger(newregister.class.getName()).log(Level.SEVERE,null,e);
           JOptionPane.showMessageDialog(this," enter valid details");
          // new newregister().setVisible(true);
          
             
          
       }
    this.setVisible(false);
       new login().setVisible(true);
       
               // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    }    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newregister().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    // End of variables declaration//GEN-END:variables

    void setvisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
