import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.SQLException;
import javax.swing.JOptionPane;/*
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PRATAP KUMAR
 */
public class placeorde extends javax.swing.JFrame {

    /**
     * Creates new form placeorde
     */
    public placeorde() {
        initComponents();
        //Connection conn=null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1850, 1080));
        setPreferredSize(new java.awt.Dimension(1720, 995));
        getContentPane().setLayout(null);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 30, 140, 37);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("Logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1460, 30, 150, 37);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("Slelect area");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(550, 160, 260, 42);

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "guntur", "prakasam", "west godavari", "nellore", "krishna", "chittoor", "kadapa", "kurnool", "anatapur", "visakhapatham", "vizianagaram" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(940, 160, 310, 48);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Select The Crop");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(540, 260, 290, 42);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cotton", "Wheat", "Maize", "Pulses", "Ground Nuts" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(940, 240, 310, 48);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("No of Quintas available");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(540, 350, 360, 42);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(940, 330, 330, 48);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(940, 430, 310, 48);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("No of Quintas to Book");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(540, 460, 350, 42);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(790, 560, 270, 51);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images-of-amazing-nature-greenery-8-backgrounds-amazing-green-nature-dezineguide-on-images-of-greenery-hd-for-laptop-grass.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1700, 910);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        workWithDatabase();
    }
     public void workWithDatabase()
    {
        //String a=(String) jComboBox1.getSelectedItem();
        //String d=jTextField1.getText();
         Connection c=null;
         Statement  s=null;
         ResultSet rs=null;
         int flag=0;
         //String N=jTextField1.getText();
         //String F=jTextField2.getText();
        //int N1=Integer.parseInt(N);
        //int F1=Integer.parseInt(F);
        //int N1=N1-F1;
         //N1=N1-N2
       //new recepit(a,b,e,d,N1,f).setVisible(true);
       
         try
   {
       Class.forName("com.mysql.jdbc.Driver");
       c=DriverManager.getConnection("jdbc:mysql://localhost/farming","root","");
       s=c.createStatement();
       String a=(String)jComboBox1.getSelectedItem();
       //e=(String) jComboBox3.getSelectedItem();
      String q1=a;
       //String q2=e;
       //rs=s.executeQuery("select quantity from crop where cname="+"'"+q1+"'");
      String bid=jTextField2.getText();
      int id=Integer.parseInt(bid);
      rs=s.executeQuery("select quantity from crop where cname="+"'"+q1+"'");
      //rs=s.executeQuery("select  from table3 where theatre="+"'"+q1+"'"+" and shows="+"'"+q2+"'");
       while(rs.next())
     {
    String id1=rs.getString("quantity");
     int id2=Integer.parseInt(id1);
     
     id2=id2-id;
     
     s.executeUpdate("Update crop set quantity="+id2+" where cname="+"'"+q1+"'");
    }
    //new recepit(a,b,e,d).setVisible(true);
       while(rs.next())
       {
               String quantity1=rs.getString("quantity");
               String q3 = quantity1;
               
               //jLabel5 = new javax.swing.JLabel("tickets available:"+"  "+q3);
               
         }
              
     
      //rs.close;
      //s.close;
      //c.close;
   }    
         catch(SQLException | ClassNotFoundException e1)
         {
             System.out.println(e1);
         }            
         

        JOptionPane.showMessageDialog(this,"registered successfully");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.setVisible(false);new home().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.setVisible(false); new logout().setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    String a=(String) jComboBox1.getSelectedItem();
 workWithDatabase1();
    }
    public void workWithDatabase1()
    {
         Connection c=null;
         Statement  s=null;
         ResultSet rs=null;
         int flag=0;
    
         //if(s1.equals("submit"))
   {
   try
   {
       Class.forName("com.mysql.jdbc.Driver");
       c=DriverManager.getConnection("jdbc:mysql://localhost/farming","root","");
       s=c.createStatement();
       String a=(String) jComboBox1.getSelectedItem();
      // String b=jPasswordField1.getText();
      System.out.println(a);
       rs=s.executeQuery("select quantity from crop where cname='"+a+"'");
       while(rs.next())
       {       //flag=1;
              // String ename=rs.getString("fullname");
              
               String survey=rs.getString("quantity");
             
               jTextField1.setText(survey);
       }
   }
        
        
   catch(Exception e)
     {
          System.out.println(e);
      }
   }
       
     // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(placeorde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(placeorde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(placeorde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(placeorde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new placeorde().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
