import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import e_Agriculture.e_agriculture;
import java.sql.SQLException;
import javax.swing.JOptionPane;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PRATAP KUMAR
 */
public class update extends javax.swing.JFrame {
Connection conn=null;
    /**
     * Creates new form update
     */
    public update() {
        initComponents();
        Connection conn=null;
        conn=e_agriculture.ConnecrDb(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1850, 1080));
        setPreferredSize(new java.awt.Dimension(1720, 995));
        getContentPane().setLayout(null);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton3.setText("Logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1441, 13, 141, 51);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(38, 21, 123, 51);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Aadhar No");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(440, 120, 257, 42);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Full Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(440, 190, 158, 42);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("New Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(440, 280, 226, 42);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Phone No");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(440, 370, 148, 42);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Address");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(440, 430, 125, 42);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Area of Land");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(440, 510, 204, 42);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Type of Soil");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(440, 600, 181, 42);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("Survey No");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(440, 680, 158, 42);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton4.setText("Get Details");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(430, 760, 203, 51);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(900, 760, 210, 51);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(850, 122, 232, 40);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(850, 188, 224, 40);

        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(850, 280, 240, 40);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(850, 360, 241, 30);

        jTextField4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(jTextField4);
        jTextField4.setBounds(850, 428, 241, 30);

        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(jTextField5);
        jTextField5.setBounds(850, 510, 241, 40);

        jTextField6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(jTextField6);
        jTextField6.setBounds(850, 600, 241, 34);

        jTextField7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(jTextField7);
        jTextField7.setBounds(850, 660, 241, 34);

        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/38974425-farming-wallpapers.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 10, 1680, 930);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
          try{
          Connection c=null;
         Statement  s=null;
         ResultSet rs=null;
         int flag=0;
           Class.forName("com.mysql.jdbc.Driver");
       c=DriverManager.getConnection("jdbc:mysql://localhost/farming","root","");
       s=c.createStatement();
      String a=jTextField2.getText();
      String s1=("UPDATE register SET fullname=?,password=?,phone_no=?,address=?,area=?,type=?,survey_no=? where aadhar_no="+a);
    /* PreparedStatement s2 =conn.prepareStatement(s1);    
     s2.setString(1,jTextField1.getText());
      s2.setString(2,jPasswordField1.getText());
      s2.setString(3,jTextField3.getText());
      s2.setString(4,jTextField4.getText());
      s2.setString(5,jTextField5.getText());
      s2.setString(6,jTextField6.getText());
      s2.setString(7,jTextField7.getText());
      s2.executeUpdate(s1);*/
     String b=jPasswordField1.getText();
       String i=jTextField3.getText();
       String d=jTextField4.getText();
       String k=jTextField5.getText();
       String f=jTextField6.getText();
       String g=jTextField7.getText();
      if(  "".equals(b) && "".equals(i) &&  "".equals(d) && "".equals(k) && "".equals(f) && "".equals(g) )
       {
           JOptionPane.showMessageDialog(this,"please enter valid details");
       }
      else if(  i.length()==10 && a.length()==12)
      {
          
      JOptionPane.showMessageDialog(null,"succesfully upated"); 
      }
      else 
      {
          
      JOptionPane.showMessageDialog(null,"plese enter valid details ");
      }
      
      /*s2.setString(1,jTextField1.getText());
      
       String b=jPasswordField1.getText();
       String i=jTextField3.getText();
       String d=jTextField4.getText();
       String k=jTextField5.getText();
       String f=jTextField6.getText();
       String g=jTextField7.getText();*/
       // Statement s2 =conn.createStatement();
       //String h=jTextField2.getText();
       
    
      
      /* if("".equals(h) && "".equals(b) && "".equals(i) &&  "".equals(d) && "".equals(k) && "".equals(f) && "".equals(g) )
       {
           JOptionPane.showMessageDialog(this,"please enter valid details");
       }
       else {
          
          Statement s2 =conn.createStatement();
        //  String s3=("insert into register values('"+h+"','"+a+"','"+b+"','"+c+"','"+d+"','"+k+"','"+f+"','"+g+"');");
          System.out.println("success");
          s.executeUpdate(s1);
      
      // JOptionPane.showMessageDialog(this," enter valid details");
          // new newregister().setVisible(true);
            
          
    }
      */
          }
          
          catch(Exception e)
     {
          System.out.println(e);
      }
      
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.setVisible(false);   new home().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.setVisible(false);   new logout().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 String a=jTextField2.getText();
       /** String b=jTextField2.getText();
        String c=jTextField3.getText();
        String d=jTextField4.getText();
        String k=jTextField5.getText();
        String f=jTextField6.getText();
        String g=jTextField7.getText();**/
 workWithDatabasee();
    }

    public void workWithDatabasee()
    {
         Connection c=null;
         Statement  s=null;
         ResultSet rs=null;
         int flag=0;
    
         //if(s1.equals("submit"))
   {
   try
   {
       Class.forName("com.mysql.jdbc.Driver");
       c=DriverManager.getConnection("jdbc:mysql://localhost/farming","root","");
       s=c.createStatement();
       String a=jTextField2.getText();
      // String b=jPasswordField1.getText();
      System.out.println(a);
       rs=s.executeQuery("select fullname,password,phone_no,address,area,type,survey_no from register where aadhar_no='"+a+"'");
       while(rs.next())
       {       //flag=1;
               String ename=rs.getString("fullname");
               String pass=rs.getString("password");
               String ph=rs.getString("phone_no");
               String add=rs.getString("address");
               String land=rs.getString("area");
               String type=rs.getString("type");
               String survey=rs.getString("survey_no");
               jPasswordField1.setText(pass);
               jTextField3.setText(ph);
               jTextField4.setText(add);
               jTextField5.setText(land);
               jTextField6.setText(type);
               jTextField7.setText(survey);
               jTextField1.setText(ename);
                if(  "".equals(a) && "".equals(ename) && "".equals(pass) &&  "".equals(ph) && "".equals(add) && "".equals(land) && "".equals(survey) && ph.length()>10  )
       {
           JOptionPane.showMessageDialog(this,"please enter valid details");
       }
       }
   }
        
        
   catch(Exception e)
     {
          System.out.println(e);
      }
   }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
     /*   {  String ph = jTextField3.getText();
        if("".equals(ph) && ph.length()>10)
       {
           JOptionPane.showMessageDialog(this,"please enter valid details");
       }   
        }// TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed
*/
    /**
     * @param args the command line arguments
   } */
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
